# Generated by gallery/generate.py; do not edit.
function morered_gallery:clear
# block-and_2_gate: and_2_gate representative state
setblock 174 99 174 minecraft:stone
setblock 174 100 174 morered:and_2_gate[facing=down,rotation=0]
# block-and_gate: and_gate representative state
setblock 177 99 174 minecraft:stone
setblock 177 100 174 morered:and_gate[facing=down,rotation=1]
# block-bitwise_and_gate: bitwise_and_gate representative state
setblock 180 99 174 minecraft:stone
setblock 180 100 174 morered:bitwise_and_gate[facing=down,rotation=2]
# block-bitwise_diode: bitwise_diode representative state
setblock 183 99 174 minecraft:stone
setblock 183 100 174 morered:bitwise_diode[facing=down,rotation=3]
# block-bitwise_not_gate: bitwise_not_gate representative state
setblock 186 99 174 minecraft:stone
setblock 186 100 174 morered:bitwise_not_gate[facing=down,rotation=0]
# block-bitwise_or_gate: bitwise_or_gate representative state
setblock 189 99 174 minecraft:stone
setblock 189 100 174 morered:bitwise_or_gate[facing=down,rotation=1]
# block-bitwise_xnor_gate: bitwise_xnor_gate representative state
setblock 192 99 174 minecraft:stone
setblock 192 100 174 morered:bitwise_xnor_gate[facing=down,rotation=2]
# block-bitwise_xor_gate: bitwise_xor_gate representative state
setblock 174 99 177 minecraft:stone
setblock 174 100 177 morered:bitwise_xor_gate[facing=down,rotation=3]
# block-bundled_cable_post: bundled_cable_post representative state
setblock 177 99 177 minecraft:stone
setblock 177 100 177 morered:bundled_cable_post[facing=down]
# block-bundled_cable_relay_plate: bundled_cable_relay_plate representative state
setblock 180 99 177 minecraft:stone
setblock 180 100 177 morered:bundled_cable_relay_plate[facing=down]
# block-diode: diode representative state
setblock 183 99 177 minecraft:stone
setblock 183 100 177 morered:diode[facing=down,rotation=2]
# block-hexidecrubrometer: hexidecrubrometer representative state
setblock 186 99 177 minecraft:stone
setblock 186 100 177 morered:hexidecrubrometer[face=floor,facing=north,power=0]
# block-latch: latch representative state
setblock 189 99 177 minecraft:stone
setblock 189 100 177 morered:latch[facing=down,rotation=0]
# block-multiplexer: multiplexer representative state
setblock 192 99 177 minecraft:stone
setblock 192 100 177 morered:multiplexer[facing=down,rotation=1,input_b=false]
# block-nand_2_gate: nand_2_gate representative state
setblock 174 99 180 minecraft:stone
setblock 174 100 180 morered:nand_2_gate[facing=down,rotation=2]
# block-nand_gate: nand_gate representative state
setblock 177 99 180 minecraft:stone
setblock 177 100 180 morered:nand_gate[facing=down,rotation=3]
# block-nor_gate: nor_gate representative state
setblock 180 99 180 minecraft:stone
setblock 180 100 180 morered:nor_gate[facing=down,rotation=0]
# block-not_gate: not_gate representative state
setblock 183 99 180 minecraft:stone
setblock 183 100 180 morered:not_gate[facing=down,rotation=1]
# block-or_gate: or_gate representative state
setblock 186 99 180 minecraft:stone
setblock 186 100 180 morered:or_gate[facing=down,rotation=2]
# block-pulse_gate: pulse_gate representative state
setblock 189 99 180 minecraft:stone
setblock 189 100 180 morered:pulse_gate[facing=down,rotation=3,input_b=false]
# block-redwire_post: redwire_post representative state
setblock 192 99 180 minecraft:stone
setblock 192 100 180 morered:redwire_post[facing=down]
# block-redwire_post_plate: redwire_post_plate representative state
setblock 174 99 183 minecraft:stone
setblock 174 100 183 morered:redwire_post_plate[facing=down]
# block-redwire_post_relay_plate: redwire_post_relay_plate representative state
setblock 177 99 183 minecraft:stone
setblock 177 100 183 morered:redwire_post_relay_plate[facing=down]
# block-soldering_table: soldering_table representative state
setblock 180 99 183 minecraft:stone
setblock 180 100 183 morered:soldering_table
# block-stone_plate: stone_plate representative state
setblock 183 99 183 minecraft:stone
setblock 183 100 183 morered:stone_plate[facing=down,rotation=0]
# block-xnor_gate: xnor_gate representative state
setblock 186 99 183 minecraft:stone
setblock 186 100 183 morered:xnor_gate[facing=down,rotation=1]
# block-xor_gate: xor_gate representative state
setblock 189 99 183 minecraft:stone
setblock 189 100 183 morered:xor_gate[facing=down,rotation=2]
# wire-red_alloy_wire-west: red_alloy_wire connected floor pair
setblock 174 99 190 minecraft:stone
setblock 174 100 190 morered:red_alloy_wire[down=true]
# wire-red_alloy_wire-east: red_alloy_wire connected floor pair
setblock 175 99 190 minecraft:stone
setblock 175 100 190 morered:red_alloy_wire[down=true]
# wire-bundled_network_cable-west: bundled_network_cable connected floor pair
setblock 178 99 190 minecraft:stone
setblock 178 100 190 morered:bundled_network_cable[down=true]
# wire-bundled_network_cable-east: bundled_network_cable connected floor pair
setblock 179 99 190 minecraft:stone
setblock 179 100 190 morered:bundled_network_cable[down=true]
# wire-white_network_cable-west: white_network_cable connected floor pair
setblock 182 99 190 minecraft:stone
setblock 182 100 190 morered:white_network_cable[down=true]
# wire-white_network_cable-east: white_network_cable connected floor pair
setblock 183 99 190 minecraft:stone
setblock 183 100 190 morered:white_network_cable[down=true]
# wire-orange_network_cable-west: orange_network_cable connected floor pair
setblock 186 99 190 minecraft:stone
setblock 186 100 190 morered:orange_network_cable[down=true]
# wire-orange_network_cable-east: orange_network_cable connected floor pair
setblock 187 99 190 minecraft:stone
setblock 187 100 190 morered:orange_network_cable[down=true]
# wire-magenta_network_cable-west: magenta_network_cable connected floor pair
setblock 190 99 190 minecraft:stone
setblock 190 100 190 morered:magenta_network_cable[down=true]
# wire-magenta_network_cable-east: magenta_network_cable connected floor pair
setblock 191 99 190 minecraft:stone
setblock 191 100 190 morered:magenta_network_cable[down=true]
# wire-light_blue_network_cable-west: light_blue_network_cable connected floor pair
setblock 194 99 190 minecraft:stone
setblock 194 100 190 morered:light_blue_network_cable[down=true]
# wire-light_blue_network_cable-east: light_blue_network_cable connected floor pair
setblock 195 99 190 minecraft:stone
setblock 195 100 190 morered:light_blue_network_cable[down=true]
# wire-yellow_network_cable-west: yellow_network_cable connected floor pair
setblock 174 99 194 minecraft:stone
setblock 174 100 194 morered:yellow_network_cable[down=true]
# wire-yellow_network_cable-east: yellow_network_cable connected floor pair
setblock 175 99 194 minecraft:stone
setblock 175 100 194 morered:yellow_network_cable[down=true]
# wire-lime_network_cable-west: lime_network_cable connected floor pair
setblock 178 99 194 minecraft:stone
setblock 178 100 194 morered:lime_network_cable[down=true]
# wire-lime_network_cable-east: lime_network_cable connected floor pair
setblock 179 99 194 minecraft:stone
setblock 179 100 194 morered:lime_network_cable[down=true]
# wire-pink_network_cable-west: pink_network_cable connected floor pair
setblock 182 99 194 minecraft:stone
setblock 182 100 194 morered:pink_network_cable[down=true]
# wire-pink_network_cable-east: pink_network_cable connected floor pair
setblock 183 99 194 minecraft:stone
setblock 183 100 194 morered:pink_network_cable[down=true]
# wire-gray_network_cable-west: gray_network_cable connected floor pair
setblock 186 99 194 minecraft:stone
setblock 186 100 194 morered:gray_network_cable[down=true]
# wire-gray_network_cable-east: gray_network_cable connected floor pair
setblock 187 99 194 minecraft:stone
setblock 187 100 194 morered:gray_network_cable[down=true]
# wire-light_gray_network_cable-west: light_gray_network_cable connected floor pair
setblock 190 99 194 minecraft:stone
setblock 190 100 194 morered:light_gray_network_cable[down=true]
# wire-light_gray_network_cable-east: light_gray_network_cable connected floor pair
setblock 191 99 194 minecraft:stone
setblock 191 100 194 morered:light_gray_network_cable[down=true]
# wire-cyan_network_cable-west: cyan_network_cable connected floor pair
setblock 194 99 194 minecraft:stone
setblock 194 100 194 morered:cyan_network_cable[down=true]
# wire-cyan_network_cable-east: cyan_network_cable connected floor pair
setblock 195 99 194 minecraft:stone
setblock 195 100 194 morered:cyan_network_cable[down=true]
# wire-purple_network_cable-west: purple_network_cable connected floor pair
setblock 174 99 198 minecraft:stone
setblock 174 100 198 morered:purple_network_cable[down=true]
# wire-purple_network_cable-east: purple_network_cable connected floor pair
setblock 175 99 198 minecraft:stone
setblock 175 100 198 morered:purple_network_cable[down=true]
# wire-blue_network_cable-west: blue_network_cable connected floor pair
setblock 178 99 198 minecraft:stone
setblock 178 100 198 morered:blue_network_cable[down=true]
# wire-blue_network_cable-east: blue_network_cable connected floor pair
setblock 179 99 198 minecraft:stone
setblock 179 100 198 morered:blue_network_cable[down=true]
# wire-brown_network_cable-west: brown_network_cable connected floor pair
setblock 182 99 198 minecraft:stone
setblock 182 100 198 morered:brown_network_cable[down=true]
# wire-brown_network_cable-east: brown_network_cable connected floor pair
setblock 183 99 198 minecraft:stone
setblock 183 100 198 morered:brown_network_cable[down=true]
# wire-green_network_cable-west: green_network_cable connected floor pair
setblock 186 99 198 minecraft:stone
setblock 186 100 198 morered:green_network_cable[down=true]
# wire-green_network_cable-east: green_network_cable connected floor pair
setblock 187 99 198 minecraft:stone
setblock 187 100 198 morered:green_network_cable[down=true]
# wire-red_network_cable-west: red_network_cable connected floor pair
setblock 190 99 198 minecraft:stone
setblock 190 100 198 morered:red_network_cable[down=true]
# wire-red_network_cable-east: red_network_cable connected floor pair
setblock 191 99 198 minecraft:stone
setblock 191 100 198 morered:red_network_cable[down=true]
# wire-black_network_cable-west: black_network_cable connected floor pair
setblock 194 99 198 minecraft:stone
setblock 194 100 198 morered:black_network_cable[down=true]
# wire-black_network_cable-east: black_network_cable connected floor pair
setblock 195 99 198 minecraft:stone
setblock 195 100 198 morered:black_network_cable[down=true]
# cross-red_alloy_wire-center: red_alloy_wire floor cross
setblock 176 99 203 minecraft:stone
setblock 176 100 203 morered:red_alloy_wire[down=true]
# cross-red_alloy_wire-west: red_alloy_wire floor cross
setblock 175 99 203 minecraft:stone
setblock 175 100 203 morered:red_alloy_wire[down=true]
# cross-red_alloy_wire-east: red_alloy_wire floor cross
setblock 177 99 203 minecraft:stone
setblock 177 100 203 morered:red_alloy_wire[down=true]
# cross-red_alloy_wire-north: red_alloy_wire floor cross
setblock 176 99 202 minecraft:stone
setblock 176 100 202 morered:red_alloy_wire[down=true]
# cross-red_alloy_wire-south: red_alloy_wire floor cross
setblock 176 99 204 minecraft:stone
setblock 176 100 204 morered:red_alloy_wire[down=true]
# cross-bundled_network_cable-center: bundled_network_cable floor cross
setblock 187 99 203 minecraft:stone
setblock 187 100 203 morered:bundled_network_cable[down=true]
# cross-bundled_network_cable-west: bundled_network_cable floor cross
setblock 186 99 203 minecraft:stone
setblock 186 100 203 morered:bundled_network_cable[down=true]
# cross-bundled_network_cable-east: bundled_network_cable floor cross
setblock 188 99 203 minecraft:stone
setblock 188 100 203 morered:bundled_network_cable[down=true]
# cross-bundled_network_cable-north: bundled_network_cable floor cross
setblock 187 99 202 minecraft:stone
setblock 187 100 202 morered:bundled_network_cable[down=true]
# cross-bundled_network_cable-south: bundled_network_cable floor cross
setblock 187 99 204 minecraft:stone
setblock 187 100 204 morered:bundled_network_cable[down=true]
# hexidecrubrometer-power-15: hexidecrubrometer maximum power state
setblock 194 99 203 minecraft:stone
setblock 194 100 203 morered:hexidecrubrometer[face=floor,facing=north,power=15]
# multiplexer-input-b: multiplexer switched input state
setblock 197 99 203 minecraft:stone
setblock 197 100 203 morered:multiplexer[facing=down,rotation=0,input_b=true]
# pulse-gate-input-b: pulse gate switched input state
setblock 200 99 203 minecraft:stone
setblock 200 100 203 morered:pulse_gate[facing=down,rotation=0,input_b=true]
# stock-control: stone stock rendering control
setblock 203 99 203 minecraft:stone
setblock 203 100 203 minecraft:stone
function morered_gallery:verify
